level_list = []

level_trivial = [
    "P X G",
    "X   X",
    "XXXXX",
]

level_trivial2 = [
    "P XXX G",
    "XR    X",
    "X XXX X",
    "X   XXX",
    "XXXXXXX",
]

level_1 = [
" PXXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X WW  XXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"XD     XXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X    XXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXX XXXXXXXXXXXXXX",
"X XXXXXXXX XXXXXXXXXXXXXX",
"X XXXXXXXX XXXXXXXXXXXXXX",
"X XXXXXXXXSXXXXXXXXXXXXXX",
"X XXXXXXXX XXXXXXXXXXXXXX",
"X                       X",
"XXXXXXXXXXXXXXXXXXXXXXXGX",
]

level_2 = [
" PXXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XX XXXXXXXXXXXXXXXXXXXX",
"X XXSXXXXXXXXXXXXXXXXXXXX",
"X     XXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X XXXXXXXXXXXXXXXXXXXXXXX",
"X  XXXXXXXXXXXXXXXXXXXXXX",
"XR          XXXXXXXXXXXXX",
"X XXXXXXXXX XXXXXXXXXXXXX",
"X XXXXXXXXX XXXXXXXXXXXXX",
"X XXXXXXXXX XXXXXXXXXXXXX",
"X XXXXXXXXX XXXXXXXXXXXXX",
"X    XXXXXX XXXXXXXXXXXXX",
"X XXXXXXXXX          XXXX",
"X XXXXXXXXX XXXXXXXX XXXX",
"X XXXXXXXXXXXXXXXXXX XXXX",
"XUXXXXXXXXXXXXXXXXXX XXXX",
"X XXXXXXXXX XXXXXXXX XXXX",
"X XXXXXXXXX XXXXXXXX XXXX",
"X XXXXXXXXX XXXXXXXX XXXX",
"X W X     R             X",
"XXXXXXXXXXXXXXXXXXXXXXXGX"
]

level_3 = [
"XPXXXXXXXXXXXXXXXXXXXXXXX",
"X     X       X         X",
"X XXX X XXX X   XXXXX X X",
"X     X X   X X   X   X X",
"X XXXXXXX XXX XXX X XXX X",
"X         X X   X X   X X",
"XX XXXXXX X XXX XXXXX   X",
"X     X     X X         X",
"X XXXXX X X X XXXXXXXXX X",
"X X     X X X X     X   X",
"XXX XXXXX X X X XXX   XXX",
"X   X   X X X X   X X   X",
"X XXX X X X X XXX X XXX X",
"X   X X X X   X   X   X X",
"XXX X X X XXX X XXXXXXXXX",
"X   X X X   X X     X   X",
"X XXX X XXX XXX XXX X X X",
"X     X X X       X X X X",
"XXXXXXX X XXXXX XXX X X X",
"X X     X     X   X   X X",
"X X XXXXX XXX XXX XXXXX X",
"X X X   X   X X   X     X",
"X X X X XXX X   XXX XXXXX",
"X   X X     X           X",
"XXXXXXXXXXXXXXXXXXXXXXXGX",
]

level_list.append(level_trivial)
level_list.append(level_trivial2)
level_list.append(level_1)
level_list.append(level_2)
level_list.append(level_3)